lsi: false
safe: true
source: [https://github.com/Sant3x/expense-tracker_fullstack/tree/expensesant3e]
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge